#! /usr/bin/env dcli

import 'dart:io';
import 'package:dcli/dcli.dart';
import './installationPreperation.dart';

/// dcli script generated by:
/// dcli create installer.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main(List<String> args) {
  InstallationPreperation.installDependencies();
  InstallationPreparation.cloneOSXKVM();
  InstallationPreparation.fetchInstaller();
  InstallationPreparation.convertToIMG();
  InstallationPreparation.createHDD(sizeGB: 20);
  InstallationPreparation.setupQuickNetworking();
  './OpenCore-Boot.sh'.run;
}
